import { useState } from 'react';

function getNextWorkingHour() {
  const now = new Date();
  const next = new Date(now);
  next.setMinutes(0, 0, 0);
  next.setHours(now.getHours() + 1);
  if (next.getHours() >= 17) {
    next.setDate(next.getDate() + 1);
    next.setHours(9, 0, 0, 0);
  } else if (next.getHours() < 9) {
    next.setHours(9, 0, 0, 0);
  }
  while (next.getDay() === 0 || next.getDay() === 6) {
    next.setDate(next.getDate() + 1);
  }
  return next;
}

function pad(n) { return String(n).padStart(2, '0'); }

function buildDescription(incident) {
  const ts = incident.timestamp
    ?? `${pad(incident.hour)}:${pad((incident.step ?? 0) * 5)} — ${incident.date}`;
  const lines = [
    'EMMA Incident Investigation Review',
    '',
    `Sensor: ${incident.sensorName}`,
    `Pollutant: ${incident.pollutant} — Peak reading: ${incident.reading} ${incident.unit}`,
    `Timestamp: ${ts}`,
  ];
  if (incident.vessel) {
    lines.push(`Likely vessel: ${incident.vessel.name} (${incident.vessel.type}, ${incident.vessel.engineType})`);
    lines.push(`IMO: ${incident.vessel.imo}`);
  }
  if (incident.windDir != null) {
    lines.push(`Wind: ${incident.windDir}° at ${incident.windSpeed ?? '—'} kn`);
  }
  if (incident.description) {
    lines.push('', incident.description);
  }
  lines.push('', 'Generated by EMMA — Emissions Monitoring & Maritime Analytics', 'Plymouth Port Authority');
  return lines.join('\n');
}

export default function ScheduleInvestigationModal({ incident, onClose, onSuccess }) {
  const defaultDt = getNextWorkingHour();
  const defaultDate = `${defaultDt.getFullYear()}-${pad(defaultDt.getMonth() + 1)}-${pad(defaultDt.getDate())}`;
  const defaultTime = `${pad(defaultDt.getHours())}:00`;

  const [title, setTitle]           = useState(`EMMA Incident Review — ${incident.sensorName} ${incident.pollutant} Spike`);
  const [date, setDate]             = useState(defaultDate);
  const [time, setTime]             = useState(defaultTime);
  const [duration, setDuration]     = useState(30);
  const [description, setDescription] = useState(buildDescription(incident));
  const [attendees, setAttendees]   = useState('');
  const [loading, setLoading]       = useState(false);
  const [error, setError]           = useState(null);

  async function handleConfirm() {
    setLoading(true);
    setError(null);
    try {
      const startISO = `${date}T${time}:00`;
      const endDt    = new Date(`${date}T${time}:00`);
      endDt.setMinutes(endDt.getMinutes() + duration);
      const endISO = `${date}T${pad(endDt.getHours())}:${pad(endDt.getMinutes())}:00`;

      const eventDetails = {
        summary: title,
        start: { dateTime: startISO, timeZone: 'Europe/London' },
        end:   { dateTime: endISO,   timeZone: 'Europe/London' },
        description,
        attendees: attendees
          .split(/[,;\n]/)
          .map(e => e.trim())
          .filter(Boolean)
          .map(email => ({ email })),
      };

      const res = await fetch('/api/schedule-investigation', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(eventDetails),
      });

      if (!res.ok) {
        let msg = `Server error ${res.status}`;
        try { const j = await res.json(); msg = j.error ?? msg; } catch {}
        throw new Error(msg);
      }
      onSuccess();
    } catch (err) {
      setError(err.message || 'Could not connect to Google Calendar — please try again');
    } finally {
      setLoading(false);
    }
  }

  return (
    <div
      style={{
        position: 'fixed', inset: 0, zIndex: 9000,
        background: 'rgba(6,14,25,0.85)', backdropFilter: 'blur(4px)',
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        padding: '16px',
      }}
      onClick={e => { if (e.target === e.currentTarget) onClose(); }}
    >
      <div
        style={{
          background: '#0a1628', border: '1px solid rgba(245,158,11,0.4)',
          borderRadius: 14, padding: '24px', width: '100%', maxWidth: 480,
          boxShadow: '0 24px 60px rgba(0,0,0,0.6)',
        }}
      >
        {/* Header */}
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
            <span style={{ fontSize: 16 }}>
              <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#f59e0b" strokeWidth="2">
                <rect x="3" y="4" width="18" height="18" rx="2" ry="2"/>
                <line x1="16" y1="2" x2="16" y2="6"/>
                <line x1="8" y1="2" x2="8" y2="6"/>
                <line x1="3" y1="10" x2="21" y2="10"/>
              </svg>
            </span>
            <span style={{ color: '#f59e0b', fontWeight: 700, fontSize: 13 }}>Schedule Investigation</span>
          </div>
          <button
            onClick={onClose}
            style={{ background: 'transparent', border: 'none', color: '#64748b', cursor: 'pointer', fontSize: 18, lineHeight: 1 }}
          >
            ✕
          </button>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
          {/* Title */}
          <Field label="Title">
            <input
              value={title} onChange={e => setTitle(e.target.value)}
              style={inputStyle}
            />
          </Field>

          {/* Date + Time row */}
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 }}>
            <Field label="Date">
              <input type="date" value={date} onChange={e => setDate(e.target.value)} style={inputStyle} />
            </Field>
            <Field label="Time">
              <input type="time" value={time} onChange={e => setTime(e.target.value)} style={inputStyle} />
            </Field>
          </div>

          {/* Duration */}
          <Field label="Duration">
            <select value={duration} onChange={e => setDuration(+e.target.value)} style={inputStyle}>
              <option value={15}>15 minutes</option>
              <option value={30}>30 minutes</option>
              <option value={45}>45 minutes</option>
              <option value={60}>60 minutes</option>
            </select>
          </Field>

          {/* Description */}
          <Field label="Description">
            <textarea
              value={description}
              onChange={e => setDescription(e.target.value)}
              rows={5}
              style={{ ...inputStyle, resize: 'vertical', fontFamily: 'Inter, monospace', lineHeight: 1.5 }}
            />
          </Field>

          {/* Attendees */}
          <Field label="Attendees" hint="Separate emails with commas">
            <input
              value={attendees}
              onChange={e => setAttendees(e.target.value)}
              placeholder="email@example.com, ..."
              style={inputStyle}
            />
          </Field>

          {/* Error */}
          {error && (
            <div style={{
              background: 'rgba(239,68,68,0.1)', border: '1px solid rgba(239,68,68,0.35)',
              borderRadius: 8, padding: '8px 12px',
            }}>
              <p style={{ color: '#ef4444', fontSize: 12 }}>{error}</p>
            </div>
          )}

          {/* Actions */}
          <div style={{ display: 'flex', gap: 8, marginTop: 4 }}>
            <button
              onClick={handleConfirm}
              disabled={loading}
              style={{
                flex: 1, padding: '10px', borderRadius: 8, border: 'none',
                background: loading ? 'rgba(245,158,11,0.4)' : '#f59e0b',
                color: '#000', fontWeight: 700, fontSize: 13, cursor: loading ? 'not-allowed' : 'pointer',
                display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 6,
              }}
            >
              {loading ? (
                <>
                  <Spinner />
                  Adding to calendar…
                </>
              ) : (
                'Confirm & Add to Calendar'
              )}
            </button>
            <button
              onClick={onClose}
              style={{
                padding: '10px 16px', borderRadius: 8,
                background: 'transparent', color: '#64748b', fontSize: 13,
                cursor: 'pointer', border: '1px solid rgba(100,116,139,0.3)',
              }}
            >
              Cancel
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

function Field({ label, hint, children }) {
  return (
    <div>
      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 4 }}>
        <label style={{ fontSize: 11, fontWeight: 600, color: '#94a3b8' }}>{label}</label>
        {hint && <span style={{ fontSize: 10, color: '#475569' }}>{hint}</span>}
      </div>
      {children}
    </div>
  );
}

function Spinner() {
  return (
    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3"
      style={{ animation: 'spin 0.8s linear infinite' }}>
      <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
      <path d="M12 2v4M12 18v4M4.93 4.93l2.83 2.83M16.24 16.24l2.83 2.83M2 12h4M18 12h4M4.93 19.07l2.83-2.83M16.24 7.76l2.83-2.83" strokeOpacity="0.3"/>
      <path d="M12 2v4" stroke="currentColor"/>
    </svg>
  );
}

const inputStyle = {
  width: '100%', background: '#060e19', color: '#e2e8f0',
  border: '1px solid rgba(29,111,164,0.4)', borderRadius: 6,
  padding: '7px 10px', fontSize: 12, outline: 'none', boxSizing: 'border-box',
};
